version: '3'
services:
  playwright-test:
    image: mcr.microsoft.com/playwright:v1.48.1-jammy
    build: .
    container_name: playwright_docker
    volumes:
      - .:/app
    working_dir: /app
    tty: true

