services:
  playwright:
    image: playwright
    build: .
    container_name: playwright_tests
    volumes:
      - .:/app
      - /app/node_modules
      - ./reports:/app/reports
    command: ["npx", "playwright", "test"]
