services:

  playwright:

    image: playwright

    build: .

    container_name: playwright_tests

    working_dir: /app

    volumes:

      - .:/app

      - /app/node_modules

      - ./playwright-report:/app/playwright-report

    command: ["npx", "playwright", "test", "--reporter=html"]
